---
title: "gapminder-wrangle"
output: html_document
---

```{r message = F}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)        ## install.packages("tidyverse")
```

```{r}
gapminder <- read_csv('data/gapminder.csv')
# gapminder
```

```{r}
filter(gapminder, lifeExp < 30)
filter(gapminder, country %in% c("Mexico", "Peru"))
```

```{r}
gap_cambodia <- filter(gapminder, country == "Cambodia") 
gap_cambodia2 <- dplyr::select(gap_cambodia, -continent, -lifeExp)
```

```{r}
gap_cambodia <- gapminder %>% 
  filter(country == "Cambodia") %>% 
  dplyr::select(-continent, -lifeExp)
```


```{r}
gapminder %>%
  mutate(gdp = pop * gdpPercap)
```

```{r}
gapminder %>%
  filter(year == 2002) %>% 
  group_by(continent) %>% 
  mutate(cont_pop = sum(pop))
```

```{r, message = F}
gapminder %>%
  group_by(continent) %>% 
  summarise(cont_pop = sum(pop)) %>% 
  ungroup()
```

```{r}
gapminder %>%
  group_by(continent, year) %>% 
  summarize(cont_pop = sum(pop))
```

```{r, message=F}
gap_max_life_exp <- gapminder %>%
  dplyr::select(-continent, -lifeExp) %>% 
  dplyr::group_by(country) %>%
  dplyr::mutate(gdp = pop * gdpPercap) %>%
  dplyr::summarize(max_gdp = max(gdp)) %>%
  dplyr::ungroup()
```

```{r, message=F}
gap_wide <- readr::read_csv('data/gapminder_wide.csv')
gapminder <- readr::read_csv('data/gapminder.csv')
gapminder
```
```{r}
gap_wide
```
```{r}
gap_long <- gap_wide %>% 
  gather(key = obstype_year,
         value = obs_values,
         dplyr::starts_with('pop'),
         dplyr::starts_with('lifeExp'), 
         dplyr::starts_with('gdpPercap')) 
str(gap_long)
```


```{r}
gap_long
```
```{r}
gap_long <- gap_wide %>% 
  gather(key = obstype_year,
         value = obs_values,
         -continent, -country)  %>% 
  separate(obstype_year,
           into = c('obs_type','year'),
           sep = '_',
           convert = T) # This ensures that the year column is an int
gap_long
```
```{r}
gapminder %>%
  filter(year==2007) %>% 
  ggplot(aes(x=gdpPercap)) + 
  geom_histogram(bins=25) + 
  scale_x_log10()
```

```{r}
canada_df <- gap_long %>% 
  filter(obs_type == "lifeExp",
         country == "Canada")
ggplot(canada_df, aes(x = year, y = obs_values)) + 
  geom_line()
```
```{r}
gap_normal <- gap_long %>% spread(obs_type, obs_values)
gap_normal
```
```{r}
gapminder %>%
  filter(year==2007) %>%
  ggplot(aes(x=gdpPercap, y = lifeExp)) + 
  geom_point(color = 'red') +
  scale_x_log10() + 
  geom_text_repel(aes(label = country), size = 2) +
  theme_classic()
```

